FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY script.js /usr/share/nginx/html/script.js
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
