FROM python:3.12-alpine
COPY main.py /
COPY requirements.txt /app/requirements.txt
RUN apk add --update --no-cache python3 py3-pip gcc musl-dev python3-dev libffi-dev openssl-dev
RUN pip3 install -r /app/requirements.txt
CMD ["python","main.py"]